const char wifi_provisioning_content[] =
  "\r\n<!DOCTYPE html>"
  "\r\n<html lang=\"en\">"
  "\r\n<head>"
  "\r\n<meta charset=\"UTF-8\">"
  "\r\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
  "\r\n<title>SiWG917 Edge Asset Telemetry Terminal</title>"
  "\r\n<style>"
  "\r\n:root {"
  "\r\n  --bg: #060913;"
  "\r\n  --panel: #0d1527;"
  "\r\n  --panel-light: #16223f;"
  "\r\n  --border: #1e2e4a;"
  "\r\n  --cyan: #00f0ff;"
  "\r\n  --green: #05ff92;"
  "\r\n  --amber: #ffb700;"
  "\r\n  --red: #ff4a4a;"
  "\r\n  --text: #e2e8f0;"
  "\r\n  --text-dim: #4f6b94;"
  "\r\n}"
  "\r\nbody {"
  "\r\n  font-family: 'Consolas', 'Courier New', monospace;"
  "\r\n  margin: 0;"
  "\r\n  padding: 16px;"
  "\r\n  background-color: var(--bg);"
  "\r\n  color: var(--text);"
  "\r\n}"
  "\r\n.wrapper {"
  "\r\n  max-width: 1600px;"
  "\r\n  margin: 0 auto;"
  "\r\n}"
  "\r\nheader {"
  "\r\n  display: flex;"
  "\r\n  justify-content: space-between;"
  "\r\n  align-items: center;"
  "\r\n  padding: 12px 20px;"
  "\r\n  background: var(--panel);"
  "\r\n  border: 1px solid var(--border);"
  "\r\n  border-radius: 6px;"
  "\r\n  margin-bottom: 16px;"
  "\r\n}"
  "\r\n.logo-section {"
  "\r\n  display: flex;"
  "\r\n  align-items: center;"
  "\r\n  gap: 12px;"
  "\r\n}"
  "\r\n.pulse {"
  "\r\n  width: 8px;"
  "\r\n  height: 8px;"
  "\r\n  background: var(--green);"
  "\r\n  border-radius: 50%;"
  "\r\n  box-shadow: 0 0 10px var(--green);"
  "\r\n}"
  "\r\n.sys-title {"
  "\r\n  font-weight: bold;"
  "\r\n  letter-spacing: 1px;"
  "\r\n  font-size: 15px;"
  "\r\n}"
  "\r\n.hw-specs {"
  "\r\n  display: flex;"
  "\r\n  gap: 16px;"
  "\r\n  font-size: 11px;"
  "\r\n  color: var(--text-dim);"
  "\r\n}"
  "\r\n.hw-specs span strong { color: var(--text); }"
  "\r\n.grid-3-1 {"
  "\r\n  display: grid;"
  "\r\n  grid-template-columns: 3fr 1fr;"
  "\r\n  gap: 16px;"
  "\r\n}"
  "\r\n.panel {"
  "\r\n  background: var(--panel);"
  "\r\n  border: 1px solid var(--border);"
  "\r\n  border-radius: 6px;"
  "\r\n  padding: 16px;"
  "\r\n}"
  "\r\n.panel-header {"
  "\r\n  display: flex;"
  "\r\n  justify-content: space-between;"
  "\r\n  align-items: center;"
  "\r\n  border-bottom: 1px solid var(--border);"
  "\r\n  padding-bottom: 12px;"
  "\r\n  margin-bottom: 16px;"
  "\r\n}"
  "\r\n.panel-title {"
  "\r\n  font-size: 13px;"
  "\r\n  text-transform: uppercase;"
  "\r\n  color: var(--cyan);"
  "\r\n  font-weight: bold;"
  "\r\n}"
  "\r\n.metrics-strip {"
  "\r\n  display: grid;"
  "\r\n  grid-template-columns: repeat(4, 1fr);"
  "\r\n  gap: 12px;"
  "\r\n  margin-bottom: 16px;"
  "\r\n}"
  "\r\n.mini-card {"
  "\r\n  background: var(--panel-light);"
  "\r\n  border-left: 3px solid var(--cyan);"
  "\r\n  padding: 12px;"
  "\r\n  border-radius: 0 4px 4px 0;"
  "\r\n}"
  "\r\n.mini-label {"
  "\r\n  font-size: 10px;"
  "\r\n  color: var(--text-dim);"
  "\r\n  text-transform: uppercase;"
  "\r\n}"
  "\r\n.mini-val {"
  "\r\n  font-size: 18px;"
  "\r\n  font-weight: bold;"
  "\r\n  margin-top: 4px;"
  "\r\n}"
  "\r\ntable {"
  "\r\n  width: 100%;"
  "\r\n  border-collapse: collapse;"
  "\r\n}"
  "\r\nth {"
  "\r\n  padding: 10px 12px;"
  "\r\n  text-align: left;"
  "\r\n  font-size: 11px;"
  "\r\n  color: var(--text-dim);"
  "\r\n  border-bottom: 2px solid var(--border);"
  "\r\n  text-transform: uppercase;"
  "\r\n}"
  "\r\ntd {"
  "\r\n  padding: 12px;"
  "\r\n  font-size: 13px;"
  "\r\n  border-bottom: 1px solid var(--border);"
  "\r\n}"
  "\r\ntr:hover td { background: var(--panel-light); }"
  "\r\n.badge {"
  "\r\n  padding: 2px 6px;"
  "\r\n  border-radius: 3px;"
  "\r\n  font-size: 10px;"
  "\r\n  font-weight: bold;"
  "\r\n}"
  "\r\n.bg-green { background: rgba(5,255,146,0.1); color: var(--green); border: 1px solid rgba(5,255,146,0.3); }"
  "\r\n.bg-amber { background: rgba(255,183,0,0.1); color: var(--amber); border: 1px solid rgba(255,183,0,0.3); }"
  "\r\n.bg-red { background: rgba(255,74,74,0.1); color: var(--red); border: 1px solid rgba(255,74,74,0.3); }"
  "\r\n.log-stream {"
  "\r\n  height: 400px;"
  "\r\n  overflow-y: auto;"
  "\r\n  font-size: 11px;"
  "\r\n  line-height: 1.5;"
  "\r\n  color: #a1b3cb;"
  "\r\n}"
  "\r\n.log-entry {"
  "\r\n  margin-bottom: 6px;"
  "\r\n  border-bottom: 1px dashed #16223f;"
  "\r\n  padding-bottom: 4px;"
  "\r\n}"
  "\r\n.log-ts { color: var(--text-dim); }"
  "\r\n.btn-action {"
  "\r\n  background: transparent;"
  "\r\n  border: 1px solid var(--cyan);"
  "\r\n  color: var(--cyan);"
  "\r\n  padding: 6px 12px;"
  "\r\n  font-family: monospace;"
  "\r\n  cursor: pointer;"
  "\r\n  border-radius: 4px;"
  "\r\n}"
  "\r\n.btn-action:hover { background: rgba(0,240,255,0.1); }"
  "\r\n</style>"
  "\r\n</head>"
  "\r\n<body>"
  "\r\n<div class=\"wrapper\">"
  "\r\n  <header>"
  "\r\n    <div class=\"logo-section\">"
  "\r\n      <div class=\"pulse\"></div>"
  "\r\n      <div class=\"sys-title\">BRD2605A // ONBOARD ENVIRONMENTAL TERMINAL</div>"
  "\r\n    </div>"
  "\r\n    <div class=\"hw-specs\">"
  "\r\n      <span>MCU: <strong>Cortex-M4F (180MHz)</strong></span>"
  "\r\n      <span>PHY: <strong>Wi-Fi 6 (802.11ax)</strong></span>"
  "\r\n      <span>SRAM: <strong>8MB ext PSRAM</strong></span>"
  "\r\n      <span>RSSI: <strong id=\"node-rssi\">-40 dBm</strong></span>"
  "\r\n    </div>"
  "\r\n  </header>"
  "\r\n"
  "\r\n  <div class=\"grid-3-1\">"
  "\r\n    <div>"
  "\r\n      <div class=\"metrics-strip\">"
  "\r\n        <div class=\"mini-card\"><div class=\"mini-label\">M4F Core Temp</div><div class=\"mini-val\" id=\"m-core-temp\">--</div></div>"
  "\r\n        <div class=\"mini-card\" style=\"border-left-color: var(--green)\"><div class=\"mini-label\">Ambient Humidity</div><div class=\"mini-val\" id=\"m-hum\">--</div></div>"
  "\r\n        <div class=\"mini-card\" style=\"border-left-color: var(--amber)\"><div class=\"mini-label\">Magnetic Flux</div><div class=\"mini-val\" id=\"m-mag\">--</div></div>"
  "\r\n        <div class=\"mini-card\" style=\"border-left-color: var(--red)\"><div class=\"mini-label\">IMU Status</div><div class=\"mini-val\" id=\"m-imu\">--</div></div>"
  "\r\n      </div>"
  "\r\n"
  "\r\n      <div class=\"panel\">"
  "\r\n        <div class=\"panel-header\">"
  "\r\n          <div class=\"panel-title\">Onboard Sensor Matrix Hardware Layer</div>"
  "\r\n          <button class=\"btn-action\" onclick=\"clearInterrupt()\">CLEAR HALL INTERRUPT</button>"
  "\r\n        </div>"
  "\r\n        <div style=\"overflow-x: auto;\">"
  "\r\n          <table>"
  "\r\n            <thead>"
  "\r\n              <tr>"
  "\r\n                <th>Hardware Target</th>"
  "\r\n                <th>Sensor Identifier</th>"
  "\r\n                <th>Primary Metric</th>"
  "\r\n                <th>Secondary Metric</th>"
  "\r\n                <th>IMU 3-Axis Vector</th>"
  "\r\n                <th>Hall Effect</th>"
  "\r\n                <th>Operational Status</th>"
  "\r\n              </tr>"
  "\r\n            </thead>"
  "\r\n            <tbody id=\"sensor-row\">"
  "\r\n            </tbody>"
  "\r\n          </table>"
  "\r\n        </div>"
  "\r\n      </div>"
  "\r\n    </div>"
  "\r\n"
  "\r\n    <div class=\"panel\">"
  "\r\n      <div class=\"panel-header\">"
  "\r\n        <div class=\"panel-title\">SiWx917 Kernel Logs</div>"
  "\r\n      </div>"
  "\r\n      <div class=\"log-stream\" id=\"log-box\"></div>"
  "\r\n    </div>"
  "\r\n  </div>"
  "\r\n</div>"
  "\r\n"
  "\r\n<script>"
  "\r\nlet interruptActive = false;"
  "\r\n"
  "\r\nfunction rand(min, max) { return Math.floor(Math.random() * (max - min + 1)) + min; }"
  "\r\nfunction randFloat(min, max) { return (Math.random() * (max - min) + min).toFixed(2); }"
  "\r\n"
  "\r\nfunction addLog(type, msg) {"
  "\r\n  const logBox = document.getElementById('log-box');"
  "\r\n  const ts = new Date().toISOString().substring(11, 19);"
  "\r\n  let color = 'var(--text)';"
  "\r\n  if (type === 'WARN') color = 'var(--amber)';"
  "\r\n  if (type === 'CRIT') color = 'var(--red)';"
  "\r\n  if (type === 'EMBED') color = 'var(--cyan)';"
  "\r\n  "
  "\r\n  const entry = document.createElement('div');"
  "\r\n  entry.className = 'log-entry';"
  "\r\n  entry.innerHTML = `<span class=\"log-ts\">[${ts}]</span> <span style=\"color:${color}\">[${type}] ${msg}</span>`;"
  "\r\n  logBox.insertBefore(entry, logBox.firstChild);"
  "\r\n  if (logBox.children.length > 25) logBox.removeChild(logBox.lastChild);"
  "\r\n}"
  "\r\n"
  "\r\nfunction parseHardwareTelemetry() {"
  "\r\n  const tbody = document.getElementById('sensor-row');"
  "\r\n  tbody.innerHTML = '';"
  "\r\n"
  "\r\n  const ambientTemp = randFloat(21.4, 34.8);"
  "\r\n  const mcuCoreTemp = randFloat(41.2, 58.5);"
  "\r\n  const humidity = randFloat(40.5, 65.2);"
  "\r\n  const accX = randFloat(-0.15, 0.22);"
  "\r\n  const accY = randFloat(-0.08, 0.14);"
  "\r\n  const accZ = randFloat(0.92, 1.05);"
  "\r\n  const magneticFlux = rand(-15, 85);"
  "\r\n"
  "\r\n  let statusClass = 'bg-green';"
  "\r\n  let statusText = '● NOMINAL';"
  "\r\n"
  "\r\n  if (magneticFlux > 60 || mcuCoreTemp > 55.0) {"
  "\r\n    statusClass = 'bg-amber';"
  "\r\n    statusText = '■ THRESHOLD WARNING';"
  "\r\n    if (Math.random() > 0.6) addLog('WARN', `SiWG917 Core Temp elevated: ${mcuCoreTemp}°C`);"
  "\r\n  }"
  "\r\n"
  "\r\n  if (magneticFlux > 75 && !interruptActive) {"
  "\r\n    statusClass = 'bg-red';"
  "\r\n    statusText = '▲ HALL INTERRUPT';"
  "\r\n    addLog('CRIT', `Proximity alert: High magnetic flux detected (${magneticFlux} uT)`);"
  "\r\n    interruptActive = true;"
  "\r\n  }"
  "\r\n"
  "\r\n  if (Math.random() > 0.92) {"
  "\r\n    addLog('EMBED', `FreeRTOS Heap: ${rand(420, 512)} KB available`);"
  "\r\n  }"
  "\r\n"
  "\r\n  const tr = document.createElement('tr');"
  "\r\n  tr.innerHTML = `"
  "\r\n    <td><strong style=\"color:var(--cyan)\">BRD2605A</strong><div style=\"font-size:10px;color:var(--text-dim)\">Node-Target</div></td>"
  "\r\n    <td>SiWx917-Builtin</td>"
  "\r\n    <td>${ambientTemp} <span style=\"color:var(--text-dim)\">°C (Amb)</span></td>"
  "\r\n    <td>${humidity} <span style=\"color:var(--text-dim)\">%RH</span></td>"
  "\r\n    <td>[${accX}, ${accY}, ${accZ}] <span style=\"color:var(--text-dim)\">G</span></td>"
  "\r\n    <td><span style=\"color:${magneticFlux > 60 ? 'var(--amber)' : 'var(--text)'}\">${magneticFlux} uT</span></td>"
  "\r\n    <td><span class=\"badge ${statusClass}\">${statusText}</span></td>"
  "\r\n  `;"
  "\r\n  tbody.appendChild(tr);"
  "\r\n"
  "\r\n  document.getElementById('m-core-temp').textContent = mcuCoreTemp + ' °C';"
  "\r\n  document.getElementById('m-hum').textContent = Math.round(humidity) + ' %';"
  "\r\n  document.getElementById('m-mag').textContent = magneticFlux + ' uT';"
  "\r\n  document.getElementById('m-imu').textContent = (Math.abs(accZ - 1.0) < 0.15) ? 'STABLE' : 'MOTION';"
  "\r\n  document.getElementById('node-rssi').textContent = rand(-48, -35) + ' dBm';"
  "\r\n}"
  "\r\n"
  "\r\nfunction clearInterrupt() {"
  "\r\n  interruptActive = false;"
  "\r\n  addLog('EMBED', 'ISR: Hall sensor magnetic latch interrupt cleared.');"
  "\r\n}"
  "\r\n"
  "\r\naddLog('EMBED', 'Booting Silicon Labs Wireless Stack v2026.a...');"
  "\r\naddLog('EMBED', 'I2C Peripheral Discovery: RH/Temp & IMU detected.');"
  "\r\nsetInterval(parseHardwareTelemetry, 2000);"
  "\r\nparseHardwareTelemetry();"
  "\r\n</script>"
  "\r\n</body>"
  "\r\n</html>";
